CREATE TABLE [dbo].[UserInformation]
(
	[Id] INT IDENTITY(1, 1) NOT NULL,
	[UserId] INT NOT NULL,
	[FirstName] NVARCHAR(50) NOT NULL,
	[LastName] NVARCHAR(50) NOT NULL,
	[PhoneNumber] NVARCHAR(50) NOT NULL,

	PRIMARY KEY CLUSTERED ([Id]ASC),
	FOREIGN KEY([UserId]) REFERENCES [dbo].[Users]([Id])
);